server.port=8085
spring.thymeleaf.cache=false
spring.datasource.generate-unique-name=false

# MongoDB properties
spring.mongodb.uri=mongodb+srv://Seunghyeon:cAgMwZbDoqtiMiyx@tacocloud.nnlauy1.mongodb.net/tacocloud